import os


NOTION_DATABASE_ID = os.getenv('NOTION_DATABASE_ID')
NOTION_TOKEN = os.getenv('NOTION_TOKEN')

GOOGLE_CLIENT_SECRET_FILE = os.getenv('GOOGLE_CLIENT_SECRET_FILE')
GOOGLE_API_NAME = os.getenv('GOOGLE_API_NAME')
GOOGLE_API_VERSION = os.getenv('GOOGLE_API_VERSION')
GOOGLE_API_SCOPES = os.getenv('GOOGLE_API_SCOPES')
