import os


NOTION_DATABASE_ID = os.getenv('NOTION_DATABASE_ID')
NOTION_TOKEN = os.getenv('NOTION_TOKEN')

GOOGLE_CLIENT_SECRET_FILE = os.getenv('GOOGLE_CLIENT_SECRET_FILE')
GOOGLE_API_NAME = os.getenv('GOOGLE_API_NAME')
GOOGLE_API_VERSION = os.getenv('GOOGLE_API_VERSION')
GOOGLE_API_SCOPES = os.getenv('GOOGLE_API_SCOPES')
GOOGLE_TASK_LIST_ID = os.getenv('GOOGLE_TASK_LIST_ID')
NOTION_TITLE_PROP_NAME = os.getenv('NOTION_TITLE_PROP_NAME')

SQLALCHEMY_DATABASE_URL = os.getenv('SQLALCHEMY_DATABASE_URL')
